import { ArrowDownRight, ArrowUpRight, Bot, Check, Clock3, GitBranch, MessageSquare, MoreHorizontal, Play, Sparkles, Users, Zap } from "lucide-react";
import { PageHeading, Panel } from "@/components/dashboard/dashboard-shell";

const stats = [
  { label: "Active agents", value: "12", delta: "+2 this month", icon: Bot, color: "#a79aff", positive: true },
  { label: "Running automations", value: "8", delta: "3 running now", icon: GitBranch, color: "#73c8ad", positive: true },
  { label: "Pending approvals", value: "6", delta: "2 need attention", icon: Check, color: "#f0b96d", positive: false },
  { label: "Tasks completed", value: "1,284", delta: "+18.6% vs last month", icon: Zap, color: "#83a7ff", positive: true },
  { label: "Leads processed", value: "86", delta: "+12.4% vs last month", icon: Users, color: "#e290c0", positive: true },
  { label: "Estimated time saved", value: "142h", delta: "This month", icon: Clock3, color: "#7cc9dc", positive: true },
];

const activity = [
  { name: "Nova", detail: "qualified a new lead", time: "2 min ago", color: "#a99aff", icon: Users },
  { name: "Atlas", detail: "resolved ticket #2048", time: "5 min ago", color: "#69c6aa", icon: MessageSquare },
  { name: "Luna", detail: "booked a product demo", time: "8 min ago", color: "#e197c6", icon: Clock3 },
  { name: "Lead Qualification", detail: "automation completed", time: "21 min ago", color: "#82a6ff", icon: GitBranch },
];

export default function DashboardPage() {
  return <main className="mx-auto max-w-[1500px] p-5 md:p-8"><PageHeading title="Your AI workforce at a glance." description="Monitor agents, automations, customers, and business activity from one place." primary="Create agent" primaryHref="/ai-agents" secondary="Create automation" secondaryHref="/automations" />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{stats.map(({ label, value, delta, icon: Icon, color, positive }) => <div key={label} className="group rounded-xl border border-[#262833] bg-[#14151d] p-4 transition hover:border-[#3a3b49]"><div className="flex items-center justify-between"><p className="text-[11px] text-[#9295a8]">{label}</p><span className="grid h-7 w-7 place-items-center rounded-lg" style={{ color, backgroundColor: `${color}13` }}><Icon size={14} strokeWidth={1.8} /></span></div><div className="mt-3 flex items-end justify-between"><p className="text-[25px] font-semibold leading-none tracking-[-0.04em] text-[#f2f3f8]">{value}</p><span className={`flex items-center gap-0.5 text-[10px] ${positive ? "text-[#75cfa7]" : "text-[#e9b96f]"}`}>{positive ? <ArrowUpRight size={12} /> : <ArrowDownRight size={12} />}{delta}</span></div></div>)}</div>

    <div className="mt-4 grid gap-4 xl:grid-cols-[1.45fr_1fr]"><Panel title="Agent performance" action="View all agents" actionHref="/ai-agents"><div className="divide-y divide-[#252630]">{[{ name: "Nova", role: "Sales Agent", score: "96.2%", tasks: "342 tasks", color: "#a99aff", bars: [45, 62, 52, 74, 58, 81, 65, 92, 70, 88, 74, 100] }, { name: "Atlas", role: "Customer Support", score: "94.8%", tasks: "286 tasks", color: "#67c5a8", bars: [60, 48, 68, 54, 74, 60, 82, 70, 88, 72, 92, 83] }, { name: "Luna", role: "Scheduling", score: "98.1%", tasks: "198 tasks", color: "#de91c2", bars: [35, 50, 42, 68, 55, 75, 64, 80, 69, 91, 76, 100] }].map((agent) => <div key={agent.name} className="flex items-center gap-3 px-4 py-3.5"><div className="grid h-8 w-8 place-items-center rounded-[10px] text-xs font-semibold" style={{ color: agent.color, backgroundColor: `${agent.color}15` }}>{agent.name[0]}</div><div className="min-w-[115px] flex-1"><p className="text-xs font-medium text-[#e6e6ed]">{agent.name}</p><p className="mt-0.5 text-[10px] text-[#85889a]">{agent.role} <span className="px-1 text-[#535565]">·</span>{agent.tasks}</p></div><div className="hidden h-8 items-end gap-[3px] sm:flex">{agent.bars.map((height, i) => <i key={i} className="w-[5px] rounded-t-[2px] opacity-80" style={{ height: `${height}%`, backgroundColor: agent.color }} />)}</div><span className="ml-3 text-xs font-semibold text-[#e6e6ed]">{agent.score}</span><MoreHorizontal size={15} className="text-[#6f7283]" /></div>)}</div></Panel>
      <Panel title="Automation activity" action="View automations" actionHref="/automations"><div className="space-y-4 px-4 py-4"><div className="flex items-center justify-between"><div><p className="text-[11px] text-[#9295a8]">Success rate</p><p className="mt-1.5 text-[26px] font-semibold tracking-[-0.04em]">97.8<span className="text-sm text-[#9a9dac]">%</span></p></div><div className="grid h-[70px] w-[70px] place-items-center rounded-full" style={{background:"conic-gradient(#8e7dff 0 78%, #272833 78% 100%)"}}><div className="grid h-[54px] w-[54px] place-items-center rounded-full bg-[#14151d] text-xs font-semibold text-[#e3e3ed]">+4.2%</div></div></div><div className="rounded-lg border border-[#272833] bg-[#111219] px-3 py-2.5"><div className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#66c9a5]" /><p className="text-[11px] font-medium text-[#e4e5eb]">Inbound Lead Qualification</p><span className="ml-auto text-[9px] text-[#7ccbaa]">ACTIVE</span></div><div className="mt-2 flex justify-between text-[10px] text-[#85889a]"><span>1,284 runs</span><span>97.8% success</span></div></div><div className="grid grid-cols-3 gap-2">{[{ v: "2,652", l: "Total runs" }, { v: "42", l: "This week" }, { v: "3", l: "Automations" }].map((x) => <div key={x.l} className="rounded-lg bg-[#111219] px-2.5 py-2"><p className="text-sm font-semibold">{x.v}</p><p className="mt-1 text-[9px] text-[#85889a]">{x.l}</p></div>)}</div></div></Panel></div>

    <div className="mt-4 grid gap-4 xl:grid-cols-[1.45fr_1fr]"><Panel title="Recent activity" action="View activity"><div className="divide-y divide-[#252630]">{activity.map(({ name, detail, time, color, icon: Icon }) => <div key={name} className="flex items-center gap-3 px-4 py-3"><span className="grid h-8 w-8 place-items-center rounded-lg" style={{ color, backgroundColor: `${color}14` }}><Icon size={14} /></span><p className="min-w-0 flex-1 truncate text-[11px] text-[#dcdee6]"><span className="font-medium text-white">{name}</span> {detail}</p><span className="whitespace-nowrap text-[10px] text-[#737687]">{time}</span></div>)}</div></Panel>
      <Panel title="Pending approvals" action="Review all"><div className="space-y-2 p-3">{[{ title: "Review Nova’s quotation", subtitle: "Meridian Labs · $4,280", type: "Quote", color: "#eab96f" }, { title: "Approve customer email", subtitle: "Atlas · Reply to ticket #2086", type: "Email", color: "#9f92ff" }, { title: "Confirm meeting invite", subtitle: "Luna · Product demo", type: "Calendar", color: "#70c8ab" }].map((item) => <div key={item.title} className="flex items-center gap-3 rounded-lg border border-[#292a35] bg-[#111219] p-3"><span className="h-1.5 w-1.5 rounded-full" style={{backgroundColor:item.color}} /><div className="min-w-0 flex-1"><p className="truncate text-[11px] font-medium text-[#e7e7ed]">{item.title}</p><p className="mt-1 truncate text-[10px] text-[#838697]">{item.subtitle}</p></div><button className="rounded-md border border-[#343541] px-2 py-1 text-[9px] text-[#d7d8e0] hover:border-[#9180ff]">Review</button></div>)}</div></Panel></div>

    <div className="mt-4 grid gap-4 xl:grid-cols-[1.45fr_1fr]"><Panel title="AI workforce activity" action="View analytics"><div className="px-4 pb-4 pt-3"><div className="mb-2 flex justify-between text-[10px] text-[#777a8b]"><span>Tasks completed</span><div className="flex gap-1 rounded-md border border-[#2a2b36] p-0.5"><button className="rounded bg-[#292632] px-2 py-1 text-[#e2dfff]">7 days</button><button className="px-2 py-1 hover:text-white">30 days</button></div></div><div className="relative h-[118px] w-full"><div className="absolute inset-0 flex flex-col justify-between">{[0,1,2,3].map((n) => <div key={n} className="border-t border-dashed border-[#292a35]" />)}</div><svg viewBox="0 0 600 118" preserveAspectRatio="none" className="absolute inset-0 h-full w-full"><defs><linearGradient id="chartFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#9180ff" stopOpacity=".2"/><stop offset="1" stopColor="#9180ff" stopOpacity="0"/></linearGradient></defs><path d="M0 96 C30 90 38 79 68 84 S112 70 136 77 S178 54 204 65 S250 47 274 56 S321 38 342 48 S385 30 410 41 S452 29 478 34 S522 19 548 25 S578 13 600 17 L600 118 L0 118Z" fill="url(#chartFill)"/><path d="M0 96 C30 90 38 79 68 84 S112 70 136 77 S178 54 204 65 S250 47 274 56 S321 38 342 48 S385 30 410 41 S452 29 478 34 S522 19 548 25 S578 13 600 17" fill="none" stroke="#9888ff" strokeWidth="2"/></svg></div><div className="mt-2 flex justify-between text-[9px] text-[#737687]">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map((d) => <span key={d}>{d}</span>)}</div></div></Panel>
      <Panel title="AI usage this month"><div className="p-4"><div className="mb-3 flex items-end justify-between"><div><p className="text-[10px] text-[#9295a8]">Token usage</p><p className="mt-1 text-lg font-semibold">8.2M <span className="text-[11px] font-normal text-[#7e8192]">/ 12M</span></p></div><Sparkles size={16} className="mb-1 text-[#a89aff]" /></div><div className="h-1.5 overflow-hidden rounded-full bg-[#292a35]"><div className="h-full w-[68%] rounded-full bg-gradient-to-r from-[#6960ed] to-[#a291ff]" /></div><div className="mt-2 flex justify-between text-[9px] text-[#818496]"><span>68% of monthly limit</span><span>$42.80 estimated</span></div><div className="mt-5 flex items-center gap-2 border-t border-[#252630] pt-3 text-[10px] text-[#828596]"><Play size={11} className="text-[#77cdaa]" />All agents operating normally</div></div></Panel></div>
  </main>;
}
